In [1]:
import pandas as pd
import numpy as np

Below, I created a small dataset of the sale of each car brand within 4 different cities.

In [7]:
products = ['Honda', 'Toyota', 'Nissan']
regions = ['New York', 'New Jersey', 'Philadelphia', 'Boston']
sales_data = np.random.randint(10000, 50000, size=(len(products), len(regions)))
print(sales_data)

[[12166 47283 27369 31667]
 [38247 17101 17663 25899]
 [17507 45608 49271 14087]]


Data tidying

In [12]:
sales_df = pd.DataFrame(sales_data, index=products, columns=regions)
print("Number of cars sold by each city:")
print(sales_df)

Number of cars sold by each city:
        New York  New Jersey  Philadelphia  Boston
Honda      12166       47283         27369   31667
Toyota     38247       17101         17663   25899
Nissan     17507       45608         49271   14087


After tidying up everything, I calculated the total sales of each cars by each company and cities.

In [14]:
sales_df = pd.DataFrame(sales_data, index=products, columns=regions)
sales_df['Total Sales'] = sales_df.sum(axis=1)
print("Number of cars sold by each city:")
print(sales_df)

Number of cars sold by each city:
        New York  New Jersey  Philadelphia  Boston  Total Sales
Honda      12166       47283         27369   31667       118485
Toyota     38247       17101         17663   25899        98910
Nissan     17507       45608         49271   14087       126473
