In [3]:
import pandas as pd
import numpy as np

Below, I created a small dataset of a teacher grading her students and the results will print out just the test results.

In [7]:
students = ['Student 1', 'Student 2', 'Student 3']
tests = ['Test 1', 'Test 2', 'Test 3']
data = np.random.randint(70, 101, size=(3, 3))
print(data)

[[95 96 81]
 [93 83 97]
 [97 96 93]]


Tidying up the Data

In [9]:
df = pd.DataFrame(data, index=students, columns=tests)
print("Test scores for each student:")
print(df)

           Test 1  Test 2  Test 3
Student 1      95      96      81
Student 2      93      83      97
Student 3      97      96      93


After tidying up everything, I calculated the average of each students test score.

In [11]:
df = pd.DataFrame(data, index=students, columns=tests)
df['Average'] = df.mean(axis=1)
print("Test scores for each student:")
print(df)

Test scores for each student:
           Test 1  Test 2  Test 3    Average
Student 1      95      96      81  90.666667
Student 2      93      83      97  91.000000
Student 3      97      96      93  95.333333
