In [1]:
import pandas as pd
import numpy as np

Created a vote poll data structure for 3 different candidates.

In [2]:
candidates = ['Candidate A', 'Candidate B', 'Candidate C']
timezones = ['Eastern', 'Central', 'Mountain', 'Pacific', 'Alaska', 'Hawaii']
votes_data = np.random.randint(10000, 50000, size=(len(candidates), len(timezones)))
print(votes_data)

[[43698 10956 22229 41870 19524 49073]
 [32082 33460 43513 35445 11512 43552]
 [11848 42697 26752 29480 12637 17202]]


Tidying up all the data and calculating the total votes of each candidate based off each time zone brackets.

In [3]:
candidates = ['Candidate A', 'Candidate B', 'Candidate C']
timezones = ['Eastern', 'Central', 'Mountain', 'Pacific', 'Alaska', 'Hawaii']
votes_data = np.random.randint(10000, 50000, size=(len(candidates), len(timezones)))

votes_df = pd.DataFrame(votes_data, index=candidates, columns=timezones)
votes_df['Total Votes'] = votes_df.sum(axis=1)

print("Vote data for each candidate:")
print(votes_df)

Vote data for each candidate:
             Eastern  Central  Mountain  Pacific  Alaska  Hawaii  Total Votes
Candidate A    48979    36651     36343    24049   20540   47069       213631
Candidate B    37462    12566     22779    48259   48750   22848       192664
Candidate C    40735    23037     10538    26659   29349   23467       153785
